### ISSUE TITLE
Can I build the custom extension on windows machine

### ISSUE THREAD

**Issue by Sourabh25** [k6io/xk6#14]
I am able to build the k6 extension for excel in mac and linux environment. Can i also build it for windows?

I also observer that the k6 extension i create on Mac works only on mac and not on linux. Is my observation correct or there is a way i can build one extension for any operating system.

**Comment by imiric** [comment]
Hi, sure, xk6 works on Windows as well. The way environment variables are specified works differently on Windows shells, and if you're building an extension that requires cgo you'll also need a C compiler installed. See [this forum post](https://community.k6.io/t/connecting-k6-to-postgres-db/1427/5) for details.

You can build k6 binaries with xk6 for all operating systems supported by Go. xk6 is simply a wrapper around calling `go` commands with a friendlier UI than doing this manually. So unless your extension uses some platform-specific features, you can cross-compile it for all platforms, but a binary compiled for one platform won't work on another, same as with any binary compiled with Go. It's simply a matter of changing the `GOOS` and `GOARCH` environment variables if you're cross-compiling (i.e. building multiple binaries on one system), otherwise Go should detect these if you're targeting the same platform you're building on.

For further questions please use the [community forum](https://community.k6.io/) or the #extensions channel on [Slack](https://k6io.slack.com).
